In [1]:
num = 1_000_000     # _ in a number is used when we have large numbers; improves readability
avg_time = 5
seconds = num * avg_time
minutes = seconds / 60
hours = minutes / 60
days = hours / 24
print('Approximate number of days =', round(days))

Approximate number of days = 58

In [5]:
total=0
num=0
while num<1_000_000:
    num=num+1
    total=total+num
print(total)

500000500000

In [8]:
total=0
x=int(input())
while x>=0:
    total=total+x
    x=int(input())
print(total)

6
6
-1
12

In [9]:
num=int(input())
max_num=0
while num>=0:
    if num>max_num:
        max_num=num
    num=int(input())
print(max_num)

5
6
-2
6

### . The break statement is used to exit out of a loop without executing any code that comes below it. For example:

In [13]:
num = 1
while True:
    if (num % 2 == 0) and (num % 3 == 0) and (num % 4 == 0):
        break
    num = num + 1
print(num)

12

### The continue statement is used to move to the next iteration of the loop, skipping whatever code comes below it. For example:

In [14]:

x = 0
while x < 50:
    x = x + 1
    if x % 3 != 0:
        continue
    print(x)

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48

In [16]:
for i in range(10,100):  #range(10, 100) represents the sequence 10, 11, ..., 99. In general, range(start, stop) represents the sequence start, start + 1, ..., stop - 1.
    print(i)

10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

### In general, range(start, stop, step) represents the sequence start, start + step, start + 2 * step, ..., last, where last is the largest element in this sequence that is less than stop. This is true when the step parameter is positive.

In [17]:
for i in range (10,100,2):
    print(i)

10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98

In [24]:
for i in range(5,5):# empty sequence
    print(i)

In [25]:
for i in range (10,5):
    print(i) # empty sequence

In [36]:
word="good"
count=1
for char in word :
    print(char,'occurs at position',count,'int the string',word)
    count+=1

g occurs at position 1 int the string good
o occurs at position 2 int the string good
o occurs at position 3 int the string good
d occurs at position 4 int the string good

In [46]:
num=int(input("enter a num:"))
fact=1
if num<0:
    print("not defined")
else:
    while num>0:
        fact=fact*num
        num=num-1
    print(fact)

enter a num:-6
not defined

In [48]:
num=abs(int(input()))
digit=1 # it cover all the digit from -9 to 9 it means we have already count single digit number now we have to count number >9
while(num>9):
    num=num//10 #  it gives only integer part and  it devied the number greater than 10 untill the number comes less than 9 
    digit=digit+1
print(digit)
#num=1234
#more than 9
#it divide 1234//10 =123
#digit becomes  2
#still 123 >9 further devies 12
#digit becomes 3 
# still 12 >9 then again devied and gives intergral part 1 
# and the digit becomes 4 finally 
# now the while loop end !

4567
4

### first n integers sum

In [4]:
print('enter a number')
n=int(input())
ans=0
for i in range(n):
    ans=ans+i
print(ans)

enter a number
10
45

In [1]:
# printing table of any letter using for loop
n=int(input())
for i in range(1,11):
    print(n,' X', i,"=",n*i)
    #print(f'{n} X {i}= {n*i}')

3
3  X 1 = 3
3  X 2 = 6
3  X 3 = 9
3  X 4 = 12
3  X 5 = 15
3  X 6 = 18
3  X 7 = 21
3  X 8 = 24
3  X 9 = 27
3  X 10 = 30

In [9]:
for i in range (10):
    print(i, end =" ")

0 1 2 3 4 5 6 7 8 9

In [10]:
d=10
m=4
y=2021
print("today date is",end=" ")
print(d,m,y,sep='-') # computer use sep as default for seprating multiple value

today date is 10-4-2021

In [14]:
pi=22/7
print(f'value of PI = {pi:.2f}') # .2f is used for value up to 2 didgit after decimal

value of PI = 3.14

In [16]:
print('{0:5d}'.format(1))
print('{0:5d}'.format(11))
print('{0:5d}'.format(111))# here 5d is ued to print the statement for the left align 
print('{0:5d}'.format(1111))#if you want to print the statement into the right allign then  remove the 5d
print('{0:5d}'.format(11111))

    1
   11
  111
 1111
11111

In [19]:
num=int(input("enter a num:"))
fact=1
if num<0:
    print("not defined")
else:
    for i in range(num,1,-1):
        fact=fact*i
    print(fact)

enter a num:-4
not defined

In [21]:
#xyz123@iitm.in
email=input()
for c in email:
    if(c=="@"):
        break
    print(c,end=' ')

rr5891@dseu.ac.in
r r 5 8 9 1

In [24]:
#xyz123@iitm.in
email=input()
for c in email:
    if(c=="@"):
        print('') # used for next line 
        continue # here it skips the value where its true and move towards the next iteration 
    print(c,end=' ')

rr5891@dseu.ac.in
r r 5 8 9 1
d s e u . a c . i n

In [26]:
for x in range(1,11):
    if x%3==0 :
        print(x)
    else:
        pass

3
6
9

In [3]:
l=[1,3,4,5,100]
print(l)
l.append(6)
print(l)

[1, 3, 4, 5, 100]
[1, 3, 4, 5, 100, 6]

In [8]:
l=[]
l.append(1)
l.append(2)
l.append(3)
print(l)
x=[]
x.append(l)

x
m=[10,20,30]
x.append(m)
x

[1, 2, 3]

[[1, 2, 3], [10, 20, 30]]

In [12]:
t=[]
t.append(x)
t.append([100,101,102])
t

[[[1, 2, 3], [10, 20, 30]], [100, 101, 102]]

In [14]:
print(t[0])
print(t[1])

[[1, 2, 3], [10, 20, 30]]
[100, 101, 102]

In [15]:
m=[]
m.append([1,2,3])
m.append([4,5,6])
m.append([7,8,9])
m

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
print(m[0])
print(m[0][0])
print(m[0][1])
print(m[0][2])

[1, 2, 3]
1
2
3

In [21]:
import random
print(random.random())#will give number between 0 to 1

0.8295408984560937

In [33]:
l=[]
#create an empty list
for i in range(30):
    l.append(random.randint(1,365))
    #append random number between 1 to 365 # append 30 of them 
print(l)

[176, 73, 239, 314, 260, 211, 306, 323, 83, 27, 51, 284, 223, 186, 210, 344, 213, 246, 50, 352, 115, 5, 113, 82, 212, 230, 98, 101, 67, 206]

In [36]:
l=[12,2,3,4,5,33,6,8]
l.sort() #no to this try to write basic code here 
l

[2, 3, 4, 5, 6, 8, 12, 33]

In [37]:
l=[1,4,5,6,7,8,9]
sum=0 
for i in range (len(l)):
    sum=sum+l[i]
print(sum)

40

In [40]:
import random 
x=random.sample(list(range(10000)),1000)
sum=0
for i in range (len(x)):
    sum=sum+x[i]
print(sum)

4903839

In [46]:
#dot product of two vectors 
x=[1,2,4,22,33]
y=[4,6,7,44,55]
sum=0
for i in range(len(x)):
    sum=sum+x[i]*y[i]
    
print(sum)

2827

In [57]:
#matrix addition by first principle 
r1=[1,2,3]
r2=[4,5,6]
r3=[7,8,9]

s1=[3,2,3]
s2=[6,5,6]
s3=[7,9,9]

A=[]
A.append(r1)
A.append(r2)
A.append(r3)

B=[]
B.append(s1)
B.append(s2)
B.append(s3)
print(A)
print(B)
dim=3

#need to add Matrx A  and matrix B
c=[[0,0,0],[0,0,0],[0,0,0]]
for i in range (dim):
    for j in range(dim):
        c[i][j]=A[i][j]+B[i][j]
print(c)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[3, 2, 3], [6, 5, 6], [7, 9, 9]]
[[4, 4, 6], [10, 10, 12], [14, 17, 18]]

In [59]:
r1=[1,2,3]
r2=[4,5,6]
r3=[7,8,9]

s1=[3,2,3]
s2=[6,5,6]
s3=[7,9,9]

A=[]
A.append(r1)
A.append(r2)
A.append(r3)

B=[]
B.append(s1)
B.append(s2)
B.append(s3)
print(A)
print(B)

#need to add Matrx A  and matrix B
c=[[0,0,0],[0,0,0],[0,0,0]]
#c[2][1] is the dot product of the 2nd row of A and the 1st columns of B
dim=3
for i in range(dim):
    for j in range(dim):
        for k in range(dim):
            c[i][j]=c[i][j]+A[i][k]*B[k][j]
print(c)

#c[i][j]=dot product of A[i][...] and B[...] [j]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[3, 2, 3], [6, 5, 6], [7, 9, 9]]
[[36, 39, 42], [84, 87, 96], [132, 135, 150]]

In [64]:
import numpy as np
x=np.mat(A)
y=np.mat(B)
print(x*y)

[[ 36  39  42]
 [ 84  87  96]
 [132 135 150]]

In [65]:
#string split and join
a='this is a string'
a=a.split(' ') # convert string to a list 
print(a)

['this', 'is', 'a', 'string']

In [66]:
a="-".join(a)
print(a)

this-is-a-string

### sum of an array

In [ ]:

sum=0
ar_count = int(input().strip())
ar = list(map(int, input().rstrip().split()))
for i in range(len(ar)):
    sum=sum+ar[i]

print(sum)

In [74]:
n=int(input())
for i in range(n):
    print(i,end="\n")

4
0
1
2
3

In [76]:
input_string = input()

# Print a string literal saying "Hello, World." to stdout.
print('Hello, World')
print(input_string)

welcome to india
Hello, World
welcome to india

In [77]:
input_string = input()
print('Hello, World')
print(input_string)

input_string = input()
print(input_string)

welcome to india
Hello, World
welcome to india
f
f

In [81]:
input_string = input()
print('Hello,World\n',input_string)

h
Hello,World
 h

In [2]:
t = int(input())
strings = [input() for _ in range(t)]

2
rohit
raesh

In [4]:
t = int(input())
for i in range(0, t):
    age = int(input())

2
12
12

In [13]:
n = int(input().strip())

arr = list(map(int, input().rstrip().split()))
for i in range(n):
    print(arr[-6:0])

4
1 2 3 4
[]
[]
[]
[]

In [16]:
import numpy as np

# Read the input
n = int(input().strip())
arr = list(map(int, input().rstrip().split()))

# Calculate the standard deviation using numpy
std_dev = np.std(arr)

# Print the result
print(f"{std_dev:.1f}")

5
10 40 30 20 50
14.1

In [9]:
def foo():
    print('I am inside foo')
foo()

I am inside foo

In [14]:
def bar():
    print('I am inside bar')
    print('I am going to call foo')
bar()

I am inside bar
I am going to call foo

In [22]:
def foo():
    print('I am inside foo')
    
def bar():
    print('I am inside bar')
    print('I am going to call foo')
bar()
foo()

I am inside bar
I am going to call foo
I am inside foo

In [28]:

def foo():
    print('hey i am here ')
    def bar():
        print('bar is inside foo')
    bar()
foo()

hey i am here
bar is inside foo

In [36]:

def square(x):
    """Return the square of x.""" # the string immediately below the function defination is called docstring 
    return x ** 2

print(square.__doc__) #This gives 'Return the square of x.' as output.
x=int(input())
square(x)

Return the square of x.

 4

16

In [41]:
def isRight(x,y,z):
   if  x**2 +y**2==z**2:
        return True
   else:
       return False

isRight(3,4,5)

True

In [45]:
def distance(x, y, metric = 'manhattan'):
    if metric == 'manhattan':
        return abs(x) + abs(y)
    elif metric == 'euclidean':
        return pow(x ** 2 + y ** 2, 0.5)
print(distance(3,4,metric='euclidean'))
print(distance(3,4)) # it takes the default value that is manhatten

5.0
7

In [19]:
def foo():
    x = 5
    print('This is a veritable fortress. None can enter here.')
    print('\N{smirking face}')
    
foo()
print(x)

This is a veritable fortress. None can enter here.
😏

NameError: name 'x' is not defined

In [12]:
y = 10
def foo():
    x = 1
    print('I can access both x and y')
    print(f'x = {x}, y = {y}')
foo()

I can access both x and y
x = 1, y = 10

,DateTime,TDS,Turbidity,pH,EC,Temperature,Summary
0,6/17/2024 3:39:41 PM,155.62,7.56,5.87,239.41,25.18,Very Good
1,6/17/2024 3:39:32 PM,105.74,4.31,7.13,162.68,26.43,Very Good
2,6/17/2024 3:39:22 PM,171.11,6.04,6.60,263.25,24.42,Very Good
3,6/17/2024 3:39:12 PM,235.21,8.16,11.83,361.86,26.16,Very Good
4,6/17/2024 3:39:01 PM,156.23,6.71,7.06,240.36,25.87,Very Good

In [35]:
import pandas as pd

data = {
    "Date": [
        "6/17/2024 ", "6/17/2024 ", "6/17/2024 ", "6/17/2024 ",
        "6/17/2024 ", "6/17/2024 ", "6/17/2024 ", "6/17/2024 ",
        "6/17/2024 ", "6/17/2024 ", "6/17/2024 ", "6/17/2024 ",
        "6/17/2024 ", "6/17/2024 ", "6/17/2024 ", "6/17/2024 ",
        "6/17/2024 ", "6/17/2024 ", "6/17/2024 ", "6/17/2024 "
    ],
    "Time": [
        "3:39:41 PM", "3:39:32 PM", "3:39:22 PM", "3:39:12 PM", "3:39:01 PM",
        "3:38:11 PM", "3:38:01 PM", "3:37:51 PM", "3:37:41 PM", "3:37:41 PM",
        "3:46:45 PM", "3:46:34 PM", "3:46:34 PM", "3:46:34 PM", "3:46:34 PM",
        "3:47:35 PM", "3:47:25 PM", "3:47:15 PM", "3:47:05 PM", "3:46:55 PM"
    ],
    "TDS": [
        155.62, 105.74, 171.11, 235.21, 156.23, 221.62, 223.83, 259.57, 289, 285,
        198.16, 289, 285, 285, 285, 103.26, 193.24, 202.41, 236.97, 136.75
    ],
    "Turbidity": [
        7.56, 4.31, 6.04, 8.16, 6.71, 5.39, 6.86, 3.07, 0, 0,
        3.36, 0, 0, 0, 0, 3.65, 6.9, 3.57, 4.51, 9.96
    ],
    "pH": [
        5.87, 7.13, 6.6, 11.83, 7.06, 7.99, 8.06, 5.16, 7.1, 7.2,
        8.52, 7.1, 7.2, 7.2, 7.2, 11.33, 8.39, 8.05, 6.71, 11.71
    ],
    "EC": [
        239.41, 162.68, 263.25, 361.86, 240.36, 340.95, 344.35, 399.35, 444.62, 438.46,
        304.87, 444.62, 438.46, 438.46, 438.46, 158.87, 297.3, 311.41, 364.58, 210.39
    ],
    "Temperature": [
        25.18, 26.43, 24.42, 26.16, 25.87, 25.67, 25.67, 26.17, 28.6, 30.5,
        24.01, 28.6, 30.5, 30.5, 30.5, 24.63, 24.52, 26.72, 26.86, 24.69
    ],
    "Summary": [
        "Very Good", "Very Good", "Very Good", "Very Good", "Very Good",
        "Very Good", "Very Good", "Very Good", "Good", "Good",
        "Very Good", "Good", "Good", "Good", "Good", "Very Good",
        "Very Good", "Very Good", "Very Good", "Very Good"
    ]
}

df = pd.DataFrame(data)

# Splitting Date_Time column into separate Date and Time columns

# Dropping the original Date_Time 
df

,Date,Time,TDS,Turbidity,pH,EC,Temperature,Summary
0,6/17/2024,3:39:41 PM,155.62,7.56,5.87,239.41,25.18,Very Good
1,6/17/2024,3:39:32 PM,105.74,4.31,7.13,162.68,26.43,Very Good
2,6/17/2024,3:39:22 PM,171.11,6.04,6.60,263.25,24.42,Very Good
3,6/17/2024,3:39:12 PM,235.21,8.16,11.83,361.86,26.16,Very Good
4,6/17/2024,3:39:01 PM,156.23,6.71,7.06,240.36,25.87,Very Good
5,6/17/2024,3:38:11 PM,221.62,5.39,7.99,340.95,25.67,Very Good
6,6/17/2024,3:38:01 PM,223.83,6.86,8.06,344.35,25.67,Very Good
7,6/17/2024,3:37:51 PM,259.57,3.07,5.16,399.35,26.17,Very Good
8,6/17/2024,3:37:41 PM,289.00,0.00,7.10,444.62,28.60,Good
9,6/17/2024,3:37:41 PM,285.00,0.00,7.20,438.46,30.50,Good
10,6/17/2024,3:46:45 PM,198.16,3.36,8.52,304.87,24.01,Very Good
11,6/17/2024,3:46:34 PM,289.00,0.00,7.10,444.62,28.60,Good
12,6/17/2024,3:46:34 PM,285.00,0.00,7.20,438.46,30.50,Good
13,6/17/2024,3:46:34 PM,285.00,0.00,7.20,438.46,30.50,Good
14,6/17/2024,3:46:34 PM,285.00,0.00,7.20,438.46,30.50,Good
15,6/17/2024,3:47:35 PM,103.26,3.65,11.33,158.87,24.63,Very Good
16,6/17/2024,3:47:25 PM,193.24,6.90,8.39,297.30,24.52,Very Good
17,6/17/2024,3:47:15 PM,202.41,3.57,8.05,311.41,26.72,Very Good
18,6/17/2024,3:47:05 PM,236.97,4.51,6.71,364.58,26.86,Very Good
19,6/17/2024,3:46:55 PM,136.75,9.96,11.71,210.39,24.69,Very Good

In [42]:
import pandas as pd
import numpy as np

# Generate a date range
dates = pd.date_range(start='6/17/2024', periods=1000, freq='D')

# Repeat the data for each date
data = {
    "Date": np.repeat(dates, 20),
    "Time": np.tile([
        "3:39:41 PM", "3:39:32 PM", "3:39:22 PM", "3:39:12 PM", "3:39:01 PM",
        "3:38:11 PM", "3:38:01 PM", "3:37:51 PM", "3:37:41 PM", "3:37:41 PM",
        "3:46:45 PM", "3:46:34 PM", "3:46:34 PM", "3:46:34 PM", "3:46:34 PM",
        "3:47:35 PM", "3:47:25 PM", "3:47:15 PM", "3:47:05 PM", "3:46:55 PM"
    ], 1000),
    "TDS": np.tile([
        155.62, 105.74, 171.11, 235.21, 156.23, 221.62, 223.83, 259.57, 289, 285,
        198.16, 289, 285, 285, 285, 103.26, 193.24, 202.41, 236.97, 136.75
    ], 1000),
    "Turbidity": np.tile([
        7.56, 4.31, 6.04, 8.16, 6.71, 5.39, 6.86, 3.07, 0, 0,
        3.36, 0, 0, 0, 0, 3.65, 6.9, 3.57, 4.51, 9.96
    ], 1000),
    "pH": np.tile([
        5.87, 7.13, 6.6, 11.83, 7.06, 7.99, 8.06, 5.16, 7.1, 7.2,
        8.52, 7.1, 7.2, 7.2, 7.2, 11.33, 8.39, 8.05, 6.71, 11.71
    ], 1000),
    "EC": np.tile([
        239.41, 162.68, 263.25, 361.86, 240.36, 340.95, 344.35, 399.35, 444.62, 438.46,
        304.87, 444.62, 438.46, 438.46, 438.46, 158.87, 297.3, 311.41, 364.58, 210.39
    ], 1000),
    "Temperature": np.tile([
        25.18, 26.43, 24.42, 26.16, 25.87, 25.67, 25.67, 26.17, 28.6, 30.5,
        24.01, 28.6, 30.5, 30.5, 30.5, 24.63, 24.52, 26.72, 26.86, 24.69
    ], 1000),
    "Summary": np.tile([
        "Very Good", "Very Good", "Very Good", "Very Good", "Very Good",
        "Very Good", "Very Good", "Very Good", "Good", "Good",
        "Very Good", "Good", "Good", "Good", "Good", "Very Good",
        "Very Good", "Very Good", "Very Good", "Very Good"
    ], 1000)
}

df = pd.DataFrame(data)

df.head(5)

,Date,Time,TDS,Turbidity,pH,EC,Temperature,Summary
0,2024-06-17,3:39:41 PM,155.62,7.56,5.87,239.41,25.18,Very Good
1,2024-06-17,3:39:32 PM,105.74,4.31,7.13,162.68,26.43,Very Good
2,2024-06-17,3:39:22 PM,171.11,6.04,6.60,263.25,24.42,Very Good
3,2024-06-17,3:39:12 PM,235.21,8.16,11.83,361.86,26.16,Very Good
4,2024-06-17,3:39:01 PM,156.23,6.71,7.06,240.36,25.87,Very Good

In [44]:
import pandas as pd
import numpy as np

# Generate a date range
dates = pd.date_range(start='6/17/2024', periods=1000, freq='D')

# Repeat the data for each date
data = {
    "Date": np.repeat(dates, 20),
    "Time": np.tile([
        "3:39:41 PM", "3:39:32 PM", "3:39:22 PM", "3:39:12 PM", "3:39:01 PM",
        "3:38:11 PM", "3:38:01 PM", "3:37:51 PM", "3:37:41 PM", "3:37:41 PM",
        "3:46:45 PM", "3:46:34 PM", "3:46:34 PM", "3:46:34 PM", "3:46:34 PM",
        "3:47:35 PM", "3:47:25 PM", "3:47:15 PM", "3:47:05 PM", "3:46:55 PM"
    ], 1000),
    "TDS": np.tile([
        155.62, 105.74, 171.11, 235.21, 156.23, 221.62, 223.83, 259.57, 289, 285,
        198.16, 289, 285, 285, 285, 103.26, 193.24, 202.41, 236.97, 136.75
    ], 1000),
    "Turbidity": np.tile([
        7.56, 4.31, 6.04, 8.16, 6.71, 5.39, 6.86, 3.07, 0, 0,
        3.36, 0, 0, 0, 0, 3.65, 6.9, 3.57, 4.51, 9.96
    ], 1000),
    "pH": np.tile([
        5.87, 7.13, 6.6, 11.83, 7.06, 7.99, 8.06, 5.16, 7.1, 7.2,
        8.52, 7.1, 7.2, 7.2, 7.2, 11.33, 8.39, 8.05, 6.71, 11.71
    ], 1000),
    "EC": np.tile([
        239.41, 162.68, 263.25, 361.86, 240.36, 340.95, 344.35, 399.35, 444.62, 438.46,
        304.87, 444.62, 438.46, 438.46, 438.46, 158.87, 297.3, 311.41, 364.58, 210.39
    ], 1000),
    "Temperature": np.tile([
        25.18, 26.43, 24.42, 26.16, 25.87, 25.67, 25.67, 26.17, 28.6, 30.5,
        24.01, 28.6, 30.5, 30.5, 30.5, 24.63, 24.52, 26.72, 26.86, 24.69
    ], 1000),
    "Summary": np.tile([
        "Very Good", "Very Good", "Very Good", "Very Good", "Very Good",
        "Very Good", "Very Good", "Very Good", "Good", "Good",
        "Very Good", "Good", "Good", "Good", "Good", "Very Good",
        "Very Good", "Very Good", "Very Good", "Very Good"
    ], 1000)
}

df = pd.DataFrame(data)

# Add "Worse" and "Bad" based on conditions
conditions = [
    (df['TDS'] > 200) & (df['Turbidity'] > 7),
    (df['pH'] > 9),
    (df['EC'] > 400),
    (df['Temperature'] > 30)
]

choices = ['Worse', 'Bad', 'Worse', 'Bad']

df['Summary'] = np.select(conditions, choices, default=df['Summary'])

df.head(30)

,Date,Time,TDS,Turbidity,pH,EC,Temperature,Summary
0,2024-06-17,3:39:41 PM,155.62,7.56,5.87,239.41,25.18,Very Good
1,2024-06-17,3:39:32 PM,105.74,4.31,7.13,162.68,26.43,Very Good
2,2024-06-17,3:39:22 PM,171.11,6.04,6.60,263.25,24.42,Very Good
3,2024-06-17,3:39:12 PM,235.21,8.16,11.83,361.86,26.16,Worse
4,2024-06-17,3:39:01 PM,156.23,6.71,7.06,240.36,25.87,Very Good
5,2024-06-17,3:38:11 PM,221.62,5.39,7.99,340.95,25.67,Very Good
6,2024-06-17,3:38:01 PM,223.83,6.86,8.06,344.35,25.67,Very Good
7,2024-06-17,3:37:51 PM,259.57,3.07,5.16,399.35,26.17,Very Good
8,2024-06-17,3:37:41 PM,289.00,0.00,7.10,444.62,28.60,Worse
9,2024-06-17,3:37:41 PM,285.00,0.00,7.20,438.46,30.50,Worse
10,2024-06-17,3:46:45 PM,198.16,3.36,8.52,304.87,24.01,Very Good
11,2024-06-17,3:46:34 PM,289.00,0.00,7.10,444.62,28.60,Worse
12,2024-06-17,3:46:34 PM,285.00,0.00,7.20,438.46,30.50,Worse
13,2024-06-17,3:46:34 PM,285.00,0.00,7.20,438.46,30.50,Worse
14,2024-06-17,3:46:34 PM,285.00,0.00,7.20,438.46,30.50,Worse
15,2024-06-17,3:47:35 PM,103.26,3.65,11.33,158.87,24.63,Bad
16,2024-06-17,3:47:25 PM,193.24,6.90,8.39,297.30,24.52,Very Good
17,2024-06-17,3:47:15 PM,202.41,3.57,8.05,311.41,26.72,Very Good
18,2024-06-17,3:47:05 PM,236.97,4.51,6.71,364.58,26.86,Very Good
19,2024-06-17,3:46:55 PM,136.75,9.96,11.71,210.39,24.69,Bad
20,2024-06-18,3:39:41 PM,155.62,7.56,5.87,239.41,25.18,Very Good
21,2024-06-18,3:39:32 PM,105.74,4.31,7.13,162.68,26.43,Very Good
22,2024-06-18,3:39:22 PM,171.11,6.04,6.60,263.25,24.42,Very Good
23,2024-06-18,3:39:12 PM,235.21,8.16,11.83,361.86,26.16,Worse
24,2024-06-18,3:39:01 PM,156.23,6.71,7.06,240.36,25.87,Very Good
25,2024-06-18,3:38:11 PM,221.62,5.39,7.99,340.95,25.67,Very Good
26,2024-06-18,3:38:01 PM,223.83,6.86,8.06,344.35,25.67,Very Good
27,2024-06-18,3:37:51 PM,259.57,3.07,5.16,399.35,26.17,Very Good
28,2024-06-18,3:37:41 PM,289.00,0.00,7.10,444.62,28.60,Worse
29,2024-06-18,3:37:41 PM,285.00,0.00,7.20,438.46,30.50,Worse

In [47]:
tds_df = pd.DataFrame(df)

file_path = 'saafwater.csv'

# Save the DataFrame to a CSV file
tds_df.to_csv(file_path, index=False)

print(f"DataFrame saved to {file_path}")

DataFrame saved to saafwater.csv

In [49]:
import os

# Get the current working directory
cwd = os.getcwd()

# Specify the file name
file_name = 'saafwater.csv'

# Create the full file path
file_path = os.path.join(cwd, file_name)

print(f"File saved at: {file_path}")

File saved at: C:\Users\HP\30Days-of-Python\saafwater.csv